### ISSUE TITLE
Moving FsExcel to a gdiplus-free ClosedXML alternative

### ISSUE THREAD

**Issue by natalie-o-perret** [misterspeedy/FsExcel#34]
[With .NET 7 which is openly gonna drop `System.Drawing.Common` stuff for non-Windows platform](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only#recommended-action), I'm wondering if FsExcel should [change the ClosedXML implementation](https://github.com/ClosedXML/ClosedXML/issues/1805) on which it relies on to something that doesn't need `System.Drawing.Common` like that [one](https://github.com/stesee/ClosedXML)?

**Comment by misterspeedy** [comment]
Hi @natalie-o-perret, sorry for the slow reply.  We are well outside my area of expertise here!

It looks like the ClosedXml folks are working on the issue you linked to, so perhaps we should apply what my old boss used to call "dynamic lethargy" - i.e. wait until their work stabilizes then use that version?

**Comment by adelarsq** [comment]
@misterspeedy The lastest ClosedXml has solved this issue, but has some breaking changes aside from this

**Comment by misterspeedy** [comment]
@adelarsq Superb - thank you. I'll integrate that version and deal with any breaking changes our end. //cc @natalie-o-perret

**Comment by adelarsq** [comment]
@misterspeedy Cool! Ping me if you need help on tests. I am using ClodedXml as fallback, but would like to go back to FsExcel when possible.

**Comment by misterspeedy** [comment]
Thank you!  Actually @emigajda already upgraded to the latest ClosedXml as part of their work on merged cells, released in 0.0.39.  So if you did have a moment to check we are now where we hoped to be that would be wonderful - thanks!

**Comment by natalie-o-perret** [comment]
> @adelarsq Superb - thank you. I'll integrate that version and deal with any breaking changes our end. //cc @natalie-o-perret

Thanks! It has been noticed ~~

I'm also curious about the perf improvement that this https://github.com/ClosedXML/ClosedXML/issues/1969 will bring, that's one of the reasons I've moved to LargeXlsx but it doesn't come without hassles on some other things: https://github.com/salvois/LargeXlsx/issues/17

**Comment by adelarsq** [comment]
> Thank you! Actually @emigajda already upgraded to the latest ClosedXml as part of their work on merged cells, released in 0.0.39. So if you did have a moment to check we are now where we hoped to be that would be wonderful - thanks!

Cool! I just did a test here and shows a exception about missing font. Now will be necessary to inform font names?

```
      An unhandled exception has occurred while executing the request.
      System.ArgumentException: Unable to find font Calibri or fallback font Microsoft Sans Serif. Install missing fonts or specify a different fallback font through 'LoadOptions.DefaultGraphicEngine = new DefaultGraphicEngine("Fallback font name")'. Additional information is available at https://closedxml.readthedocs.io/en/latest/tips/missing-font.html page.
         at ClosedXML.Graphics.DefaultGraphicEngine.LoadFont(MetricId metricId)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
         at ClosedXML.Graphics.DefaultGraphicEngine.GetFont(MetricId metricId)
         at ClosedXML.Graphics.DefaultGraphicEngine.GetFont(IXLFontBase fontBase)
         at ClosedXML.Graphics.DefaultGraphicEngine.GetTextWidth(String text, IXLFontBase fontBase, Double dpiX)
         at ClosedXML.Excel.XLColumn.GetWidthInCharacters(String text, IXLFontBase font)
         at ClosedXML.Excel.XLColumn.AdjustToContents(Int32 startRow, Int32 endRow, Double minWidth, Double maxWidth)
         at ClosedXML.Excel.XLColumn.AdjustToContents(Int32 startRow, Int32 endRow)
         at ClosedXML.Excel.XLColumn.AdjustToContents(Int32 startRow)
         at ClosedXML.Excel.XLColumn.AdjustToContents()
         at ClosedXML.Excel.XLColumns.<>c.<AdjustToContents>b__13_0(XLColumn c)
         at ClosedXML.Excel.EnumerableExtensions.ForEach[T](IEnumerable`1 source, Action`1 action)
         at ClosedXML.Excel.XLColumns.AdjustToContents()
         at FsExcel.Render.AsWorkBook(FSharpList`1 items)
         at FsExcel.Render.AsFile(String path, FSharpList`1 items)
         at server.Planilha.gerarPlanilha(DateTime dataInicial, DateTime dataFinal, FSharpList`1 list) in /app/lib/Planilha.fs:line 125
         at server.Rules.gerarPlanilha(DateTime dataInicial, DateTime dataFinal) in /app/lib/Rules.fs:line 229
         at server.Handlers.RelatorioHandlers.consultar(HttpContext ctx) in /app/lib/Handlers.fs:line 47
         at server.Program.main@52-5.Invoke(HttpContext ctx)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Comment by misterspeedy** [comment]
Ah, interesting!  I'll see if I can find a way round that.  Thank you!

**Comment by misterspeedy** [comment]
Raised as https://github.com/misterspeedy/FsExcel/issues/39

**Comment by misterspeedy** [comment]
@adelarsq what do you think of the workaround I've added in the latest comment in #41 ?
